1.to print the python version

In [5]:
import pandas as p
import numpy as n

p.__version__

'2.3.1'

Read dataframe from csv file

In [6]:
df = p.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')
df

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2155,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3060,17.3,No,2699.99
2156,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3070,17.3,No,2899.99
2157,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,32,1000,SSD,RTX 3080,17.3,No,3399.99
2158,Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...,Refurbished,Razer,Book,Intel Evo Core i7,16,1000,SSD,NaN,13.4,Yes,1899.99
2159,Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...,Refurbished,Razer,Book,Intel Evo Core i7,16,256,SSD,NaN,13.4,Yes,1699.99

2.find the number of rows in the dataframe

In [7]:
df.shape[0]

2160

3.Find the number of unique values in a column (eg Brand)

In [8]:
df['Brand'].nunique()

27

4.Find number of columns in the dataset that has missing values

In [9]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

5.Find maximum final price of Dell notebooks in the dataset

In [10]:
df['Dell' == df.Brand]['Final Price'].max()

np.float64(3936.0)

6.1 Find the median value of Screen column in the dataset.

In [11]:
df['Screen'].median()

np.float64(15.6)

6.2 calculate the most frequent value of the same Screen column, index 0 will pick the first value if there is a tie

In [15]:
screen_mode=df['Screen'].mode()[0]
df['Screen'].fillna(screen_mode)
df['Screen'].median()

np.float64(15.6)

7.1 select Innjoo laptops with fields Ram, Storage and Screen

In [23]:
innjoo_df = df[df.Brand == 'Innjoo']
innjoo_df = innjoo_df[['RAM', 'Storage', 'Screen']]
innjoo_df

      RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

7.2 Generate matrix X for Innjoo laptops with fields Ram, Storage and Screen
XTX = Result of Matrix multiplication of Transpose of X and X

In [30]:
X = innjoo_df.values
X
XTX = X.T.dot(X)
XTX
XTX_inv = n.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

7.3 create a array with values [1100, 1300, 800, 900, 1000, 1100]

In [31]:
y= n.array ([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

7.7Multiply  the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [33]:
inter_result = XTX_inv.dot(X.T)
w = inter_result.dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

7.8 sum of all the elements of the result?

In [38]:
w.sum()

np.float64(91.2998806299555)